# Generated by Django 4.1.7 on 2023-03-11 23:45

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import tutoacademy_chatApp_ms.models.chat_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatId', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('messages', djongo.models.fields.ArrayField(model_container=tutoacademy_chatApp_ms.models.chat_model.Message)),
                ('state', models.BooleanField(default=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sendTime', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
